<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Prompts\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Models\Prompts\ResponsePattern.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Pgvector" Version="0.3.2" />
  </ItemGroup>
</Project>
