<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Services\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AthenaUnionAI.Application\AthenaUnionAI.Application.csproj" />
    <ProjectReference Include="..\AthenaUnionAI.Domain\AthenaUnionAI.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic.SDK" Version="5.10.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.6" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.74.0" />
  </ItemGroup>

</Project>
